version: '3.7'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orderservice_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"

  orderservice:
    image: orderservice
    depends_on:
      - postgres
      - rabbitmq
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=orderservice_db;Username=postgres;Password=postgres"
    ports:
      - "5000:80"

volumes:
  postgres-data:
